title: Блог 8-Б класу
description: Бучанський НВК "СЗОШ 1-3 ст. №4 - ЗОШ 1-3 ст." №4
email: igor_zash@live.com
baseurl: ''
url: classblog.github.io
github_username: igorzash
paginate: 9
paginate_path: '/feed/:num'