---
title: Блог 8-Б класу
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  category:
    output: true
description: Бучанський НВК "СЗОШ 1-3 ст. №4 - ЗОШ 1-3 ст." №4
email: igor_zash@live.com
baseurl: ''
url: classblog.github.io
github_username: igorzash
paginate: 9
paginate_path: "/feed/:num"
defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"